[package]
name = "agentic"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.27", features = ["all-widgets"] }
tokio = { version = "1.0", features = ["full"] }
taffy = "0.4"
crossterm = "0.27"
