[package]
name = "agentic-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
ratatui = { workspace = true }
figment = { workspace = true }
toml = { workspace = true }
